version: "3.9"
services:
  u20.04:
    container_name: u20.24
    env_file: .env
    user: ${MY_UID}:${MY_GID}
    build: 
      context: .
      args:
        - USER=${USER}
    network_mode: "none"
    volumes:
      - /tmp/kitchen-sink:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./startup.sh:/startup.sh
